apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app1-app
  namespace: argocd
  finalizers:
    # The default behaviour is foreground cascading deletion
    - resources-finalizer.argocd.argoproj.io  
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  project: default
  source:
    repoURL: https://github.com/mehmetmgrsl/argocd-app-of-apps.git
    path: ./manifests/app1
    targetRevision: main
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true