apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app2-app
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/mehmetmgrsl/argocd-app-of-apps
    path: manifests/app2
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true