apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-app-2
spec:
  selector:
    matchLabels:
      app: app-2
  replicas: 2
  template:
    metadata:
      labels:
        app: app-2
    spec:
      containers:
      - name: app-2
        image: nginx
        ports:
        - containerPort: 8282